<div id="footerrow" class="roadline">
<!--
	<form id="findform" name="web" method="get" action="http://www.yandex.ru/yandsearch"> 
	<input id="findtext" type="text" name="text" size=76 value="" MAXLENGTH=152 />
	<input id="findcmd" type="submit" value="Найти" />
	<input type="hidden"name="serverurl" value="http://www.tam.ru/hobby" /> 
	<input type="hidden" name="server_name" value="Hobby - Главная страница" />
	</form>
-->
<hr class="hidden" />
<div class="img"></div>© <a href="http://vit-1.github.io/hobby/viT/resume/"><i>v</i>iT</a>
</div>
<div id="footer">
	<img class="banner" src="http://vit-1.github.io/hobby/banner1.gif" width="468px" height="60px" alt="Рекламный баннер" />
</div>