<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- Товарищ, помни: у каждой хорошей идеи есть свой автор! (c)viT -->
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
<meta http-equiv="Cache-Control" content="no-cache, post-check=0, pre-check=0" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="no-cache" />
<meta http-equiv="Expires" content="-1" />
<link id="screen" type="text/css" rel="stylesheet" href="http://vit-1.github.io/hobby/navigate/css/002summer/screen.css" media="screen" />
<link id="always_on" type="text/css" rel="stylesheet" href="http://vit-1.github.io/hobby/navigate/css/always_on.css" />
<link type="text/css" rel="stylesheet" href="http://vit-1.github.io/hobby/navigate/css/print.css" media="print" />
<script type="text/javascript" src="http://vit-1.github.io/hobby/navigate/scripts/cookies.js"></script>
<script type="text/javascript" src="http://vit-1.github.io/hobby/navigate/scripts/currentmenu.js"></script>
<script type="text/javascript" src="http://vit-1.github.io/hobby/navigate/scripts/fontsize.js"></script>
<script type="text/javascript" src="http://vit-1.github.io/hobby/navigate/scripts/sitestyle.js"></script>
<script type="text/javascript" src="http://vit-1.github.io/hobby/navigate/scripts/pagehandler.js"></script>
<script type="text/javascript" language="JavaScript">
<!--
window.onload = fInitEvents;
//-->
</script>